[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
select = ["E", "F", "I", "B", "UP", "ANN"]
ignore = [
  # Allow underscore-prefixed unused params in Protocols and facades
  "ANN101", "ANN102",
]

[tool.ruff.isort]
combine-as-imports = true
force-sort-within-sections = true

[tool.mypy]
python_version = "3.11"
check_untyped_defs = true
disallow_incomplete_defs = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unreachable = true
no_implicit_optional = true

[tool.pyright]
typeCheckingMode = "basic"

